In [2]:
import pandas as pd

data = pd.read_csv("../data/water_potability.csv", names = ['id', 'pH', 'Hardness', 'Solids', 'Chloramines', 'Sulfate', 'Conductivity', 'Organic Carbon', 'Trihalomethanes', 'Turbidity', 'Potability'])
df = pd.DataFrame(data)

In [3]:
# Description
desc = df.describe()

# Median
desc.loc['median'] = df.median()

# Variance
desc.loc['variance'] = df.var()

# Range
desc.loc['range'] = df.max() - df.min()

# IQR
desc.loc['IQR'] = df.quantile(0.75) - df.quantile(0.25)

# Skewness
desc.loc['skewness'] = df.skew()

# Kurtosis
desc.loc['kurtosis'] = df.kurtosis()

desc

,id,pH,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic Carbon,Trihalomethanes,Turbidity,Potability
count,2010.00000,2010.000000,2010.000000,2.010000e+03,2010.000000,2010.000000,2010.000000,2010.000000,2010.000000,2010.000000,2010.000000
mean,1005.50000,7.087193,195.969209,2.190467e+04,7.134322,333.211376,426.476708,14.357940,66.400717,3.969497,0.402985
std,580.38134,1.572803,32.643166,8.625398e+03,1.585214,41.211111,80.701872,3.325770,16.081109,0.780471,0.490620
min,1.00000,0.227499,73.492234,3.209426e+02,1.390871,129.000000,201.619737,2.200000,8.577013,1.450000,0.000000
25%,503.25000,6.090785,176.740657,1.561441e+04,6.138326,307.626986,366.619219,12.122530,55.949993,3.442882,0.000000
50%,1005.50000,7.029490,197.203525,2.092688e+04,7.142014,332.214113,423.438372,14.323286,66.482041,3.967374,0.000000
75%,1507.75000,8.053006,216.447589,2.717053e+04,8.109933,359.268147,482.209772,16.683562,77.294613,4.514663,1.000000
max,2010.00000,14.000000,317.338124,5.648867e+04,13.127000,481.030642,753.342620,27.006707,124.000000,6.494749,1.000000
median,1005.50000,7.029490,197.203525,2.092688e+04,7.142014,332.214113,423.438372,14.323286,66.482041,3.967374,0.000000
variance,336842.50000,2.473709,1065.576277,7.439749e+07,2.512904,1698.355672,6512.792113,11.060746,258.602066,0.609135,0.240708
range,2009.00000,13.772501,243.845890,5.616773e+04,11.736129,352.030642,551.722883,24.806707,115.422987,5.044749,1.000000
IQR,1004.50000,1.962221,39.706932,1.155612e+04,1.971607,51.641161,115.590553,4.561031,21.344620,1.071781,1.000000
skewness,0.00000,0.048535,-0.085321,5.910114e-01,0.013003,-0.045728,0.268012,-0.020220,-0.051383,-0.032266,0.395873
kurtosis,-1.20000,0.626904,0.525480,3.373203e-01,0.549782,0.786854,-0.237206,0.031018,0.223017,-0.049831,-1.845122

In [4]:
# Modus per kolom
# Modus id
print('Kolom id :')
print(df['id'].mode())

Kolom id :
0          1
1          2
2          3
3          4
4          5
        ...
2005    2006
2006    2007
2007    2008
2008    2009
2009    2010
Length: 2010, dtype: int64

In [5]:
# Modus pH
print('Kolom pH :')
print(df['pH'].mode())

Kolom pH :
0        0.227499
1        0.989912
2        1.431782
3        1.757037
4        1.985383
          ...
2005    11.568768
2006    11.898078
2007    12.246928
2008    13.349889
2009    14.000000
Length: 2010, dtype: float64

In [6]:
# Modus Hardness
print('Kolom Hardness :')
print(df['Hardness'].mode())

Kolom Hardness :
0        73.492234
1        77.459586
2        81.710895
3        94.091307
4        94.812545
           ...
2005    286.567991
2006    287.975540
2007    300.292476
2008    306.627481
2009    317.338124
Length: 2010, dtype: float64

In [7]:
# Modus Solids
print('Kolom Solids :')
print(df['Solids'].mode())

Kolom Solids :
0         320.942611
1        1198.943699
2        1351.906979
3        1372.091043
4        2552.962804
            ...
2005    50793.898917
2006    53735.899194
2007    55334.702799
2008    56351.396304
2009    56488.672413
Length: 2010, dtype: float64

In [8]:
# Modus Chloramines
print('Kolom Chloramines :')
print(df['Chloramines'].mode())

Kolom Chloramines :
0        1.390871
1        1.920271
2        2.397985
3        2.456014
4        2.458609
          ...
2005    12.580026
2006    12.626900
2007    12.653362
2008    13.043806
2009    13.127000
Length: 2010, dtype: float64

In [9]:
# Modus Sulfate
print('Kolom Sulfate :')
print(df['Sulfate'].mode())

Kolom Sulfate :
0       129.000000
1       180.206746
2       182.397370
3       187.170714
4       187.424131
           ...
2005    458.441072
2006    460.107069
2007    475.737460
2008    476.539717
2009    481.030642
Length: 2010, dtype: float64

In [10]:
# Modus Conductivity
print('Kolom Conductivity :')
print(df['Conductivity'].mode())

Kolom Conductivity :
0       201.619737
1       210.319182
2       233.907965
3       245.859632
4       252.968328
           ...
2005    666.690618
2006    669.725086
2007    695.369528
2008    708.226364
2009    753.342620
Length: 2010, dtype: float64

In [11]:
# Modus Organic Carbon
print('Kolom Organic Carbon :')
print(df['Organic Carbon'].mode())

Kolom Organic Carbon :
0        2.200000
1        4.371899
2        4.466772
3        4.861631
4        4.966862
          ...
2005    23.569645
2006    23.604298
2007    23.917601
2008    24.755392
2009    27.006707
Length: 2010, dtype: float64

In [12]:
# Modus Trihalomethanes
print('Kolom Trihalomethanes :')
print(df['Trihalomethanes'].mode())

Kolom Trihalomethanes :
0         8.577013
1        14.343161
2        15.684877
3        16.291505
4        17.527765
           ...
2005    114.034946
2006    114.208671
2007    116.161622
2008    120.030077
2009    124.000000
Length: 2010, dtype: float64

In [13]:
# Modus Turbidity
print('Kolom Turbidity :')
print(df['Turbidity'].mode())

Kolom Turbidity :
0       1.450000
1       1.492207
2       1.496101
3       1.680554
4       1.812529
          ...
2005    6.307678
2006    6.357439
2007    6.389161
2008    6.494249
2009    6.494749
Length: 2010, dtype: float64

In [14]:
# Modus Potability
print('Kolom Potability :')
print(df['Potability'].mode())

Kolom Potability :
0    0
dtype: int64

In [15]:
# Modus semua kolom
df.mode()

,id,pH,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic Carbon,Trihalomethanes,Turbidity,Potability
0,1,0.227499,73.492234,320.942611,1.390871,129.000000,201.619737,2.200000,8.577013,1.450000,0.0
1,2,0.989912,77.459586,1198.943699,1.920271,180.206746,210.319182,4.371899,14.343161,1.492207,NaN
2,3,1.431782,81.710895,1351.906979,2.397985,182.397370,233.907965,4.466772,15.684877,1.496101,NaN
3,4,1.757037,94.091307,1372.091043,2.456014,187.170714,245.859632,4.861631,16.291505,1.680554,NaN
4,5,1.985383,94.812545,2552.962804,2.458609,187.424131,252.968328,4.966862,17.527765,1.812529,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2005,2006,11.568768,286.567991,50793.898917,12.580026,458.441072,666.690618,23.569645,114.034946,6.307678,NaN
2006,2007,11.898078,287.975540,53735.899194,12.626900,460.107069,669.725086,23.604298,114.208671,6.357439,NaN
2007,2008,12.246928,300.292476,55334.702799,12.653362,475.737460,695.369528,23.917601,116.161622,6.389161,NaN
2008,2009,13.349889,306.627481,56351.396304,13.043806,476.539717,708.226364,24.755392,120.030077,6.494249,NaN
2009,2010,14.000000,317.338124,56488.672413,13.127000,481.030642,753.342620,27.006707,124.000000,6.494749,NaN